services:
  - type: web
    name: gta-tech-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: pgsql
      - key: DB_PORT
        value: "5432"
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://gta-tech.vercel.app
